package com.fndt.quote.controllers.util

const val ID = "id"
const val QUERY_ARG = "query"
const val TAG_ARG = "tag"
const val TAG_NAME_ARG = "name"
const val QUOTE_ID = "id"

const val AUTHOR_ENDPOINT = "/author"
const val QUOTES_ENDPOINT = "/quotes"
const val LIKE_ENDPOINT = "/like"
const val COMMENTS_ENDPOINT = "$QUOTES_ENDPOINT/{$ID}/comment"
const val POPULARS_ENDPOINT = "/popular"
const val REGISTRATION_ENDPOINT = "/register"
const val SEARCH_ENDPOINT = "/search"
const val TAG_ENDPOINT = "/tag"
const val ROLE_ENDPOINT = "/role"
const val REVIEW_ENDPOINT = "/approve"
const val REVIEW_QUOTE_ENDPOINT = "$QUOTES_ENDPOINT$REVIEW_ENDPOINT"
const val BAN_ENDPOINT = "/ban"
const val ADD_ENDPOINT = "/add"
const val REVIEW_TAG_ENDPOINT = "$TAG_ENDPOINT$REVIEW_ENDPOINT"
const val PERMANENT_BAN_ENDPOINT = "/ban/permanent"
